---
- name: Download app library archive from s3
  aws_s3:
    bucket: '{{ s3_bucket }}'
    object: '{{ s3_file_perl_lib }}'
    dest: "/tmp/{{ s3_file_perl_lib_name }}"
    mode: get
    
- name: Unarchive app library download
  unarchive:
    src: "/tmp/{{ s3_file_perl_lib_name }}"
    dest: /tmp/
    remote_src: yes

- name: Install xerces files and binaries
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: "/tmp/{{ item }}/"
    dest: "/{{ item }}"
    remote_src: yes
  with_items: '{{ xerces_paths }}'

- name: Remove temporary app library files
  file:
    path: "/tmp/{{ item }}/"
    state: absent
  with_items:
    - usr
    - etc

- name: Install libapreq2 package for httpd mod_apreq2.so module requirement
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
      name: libapreq2
      state: present

- name: Copy config templates to relevant locations
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0755
  loop:
    - etc/httpd/conf/httpd.conf.j2
    - etc/httpd/conf/startup.pl
    - etc/httpd/conf.d/perl.conf.j2

- name: Update Postfix configuration for mail relay (existing commented lines)
  lineinfile:
    dest: "/etc/postfix/{{ postfix_main_config_file }}"
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^#{{ item.key }} ="
    insertafter: "^#{{ item.key }} ="
  with_items: "{{ postfix_config }}"

- name: Update Postfix network config (existing uncommented lines)
  lineinfile:
    dest: "/etc/postfix/{{ postfix_main_config_file }}"
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^{{ item.key }} ="
  with_items: "{{ postfix_net_config }}"

- name: Enable crontab for XML user
  lineinfile:
    dest: "/etc/cron.allow"
    line: "xmltest"
    regexp: "^xmltest"

- name: Allow xmltest to use apachectl 
  copy:
    dest: "/etc/sudoers.d/xmltest"
    content: |
      # XML user
      xmltest ALL=(ALL) NOPASSWD:/usr/sbin/apachectl

- name: Disable password expiry for XML user so it doesnt break cron
  command: "chage -m 0 -M 99999 -I -1 -E -1 xmltest"

- name: Copy deployment scripts to server for later use
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_deploy_playbook_directory }}/{{ item | basename}}"
    mode: 0755
  loop:
    - deployment-scripts/frontend_deployment.yml
    - deployment-scripts/backend_deployment.yml

- name: Setup deployment playbook dependancies (1/2)
  vars:
    ansible_python_interpreter: /usr/bin/python2.6  
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_deploy_playbook_directory }}/"
    mode: 0755
  loop: 
    - requirements.yml

- name: Setup deployment playbook dependancies (2/2)
  command: "/usr/local/bin/ansible-galaxy install -f -r {{ansible_deploy_playbook_directory}}/requirements.yml"
  register: requirements_output
  changed_when: '"was installed successfully" in requirements_output.stdout'
