---  
- hosts: xml-sandpit
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.6
  roles:
    - ch_collections.heritage_services.heritage_frontend_base
    - ch_collections.enterpriselinux6.nfs
    - xml-sandpit-config
